In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data[:100, :]
target = iris.target[:100]

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state=0)

model = logistic_regression.fit(features_standardized, target)

In [2]:
new_observation = [[.5, .5, .5, .5]]

model.predict(new_observation)

array([1])

In [3]:
model.predict_proba(new_observation)

array([[0.17738424, 0.82261576]])

In [7]:
# multiclass

features, target = iris.data, iris.target

features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state=0, multi_class='multinomial')

model = logistic_regression.fit(features_standardized, target)

In [5]:
model.predict_proba(new_observation)

array([[0.0387617 , 0.40669108, 0.55454723]])

In [8]:
model.predict_proba(new_observation)

array([[0.01982185, 0.74491886, 0.23525928]])

In [11]:
# reducing variation through regularization
from sklearn.linear_model import LogisticRegressionCV

# create decision tree classifier object
logistic_regression = LogisticRegressionCV(
    penalty='l2', Cs=10, random_state=10, n_jobs=-1)

model = logistic_regression.fit(features_standardized, target)

In [12]:
model.predict_proba(new_observation)

array([[5.96244929e-04, 9.70140320e-01, 2.92634349e-02]])

In [13]:
model.predict(new_observation)

array([1])

In [14]:
# handling imbalanced classes

import numpy as np

features = features[40:, :]
target = target[40:]

# create a target vector inidicating if class 0, otherwise 1
target = np.where((target == 0), 0, 1)

features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state=0, class_weight='balanced')

model = logistic_regression.fit(features_standardized, target)